# Generated by Django 2.2.4 on 2022-06-28 08:52

from django.db import migrations, models
import valid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=45, validators=[valid.models.validateLengthGreaterThanTwo])),
                ('lname', models.CharField(max_length=45, validators=[valid.models.validateLengthGreaterThanTwo])),
                ('email', models.CharField(max_length=45, validators=[valid.models.validateLengthGreaterThanTwo])),
                ('password', models.CharField(max_length=45, validators=[valid.models.validateLengthGreaterThanTwo])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
