# Generated by Django 2.2.4 on 2020-12-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showsapp', '0002_auto_20201214_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
