# Generated by Django 2.2.4 on 2020-12-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showsapp', '0005_auto_20201216_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateField(),
        ),
    ]
